name: "HaSelenium"
version: "0.2.1"
slug: haselen
description: "Selenium automation for Home Assistant"
url: https://github.com/dimxyp/haos_addons/tree/main/haselen
panel_icon: mdi:spider-web
startup: services
boot: auto
init: false
ingress: false
arch:
  - amd64
host_network: true
options:
  zusername: "your_zenith_username"
  zpassword: "your_zenith_password"
  vusername: "your_zenith_username"
  vpassword: "your_zenith_password"
  haip: "192.168.1.100"  # Home Assistant IP
  token: "YOUR_LONG_LIVED_ACCESS_TOKEN"
  entity_id: "input_text.zenith_power"
schema:
  zusername: str
  zpassword: password
  vusername: str
  vpassword: password
  haip: str
  token: str
  entity_id: str?

